spring.application.name=SearchService
server.port=8081

# Elasticsearch Configuration
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=2m
spring.elasticsearch.username=
spring.elasticsearch.password=

spring.mvc.form.content.filter.enabled=false