apiVersion: apps/v1
kind: Deployment
metadata:
  name: USER-SERVICE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: USER-SERVICE
  template:
    metadata:
      labels:
        app: USER-SERVICE
    spec:
      containers:
        - name: USER-SERVICE
          image: user-service:latest
          ports:
            - containerPort: 8089
          env:
            - name: AWS_RDS_URL
              valueFrom:
                configMapKeyRef:
                  name: aws-rds-config
                  key: uri
            - name: AWS_RDS_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: aws-rds-secret
                    key: username
            - name: AWS_RDS_PASSWORD
              valueFrom:
                  secretKeyRef:
                     name: aws-rds-secret
                     key: password
            - name: KAFKA_SERVERS
              value: kafka:9092