apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          env:
            - name: AWS_RDS_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service
                  key: product.database
            - name: AWS_RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: AWS_RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            #            - name: EUREKA_URI
            #              valueFrom:
            #                configMapKeyRef:
            #                  key: uri
            #                  name: eureka-config
            #            - name: EUREKA_INSTANCE_HOSTNAME
            #              valueFrom:
            #                configMapKeyRef:
            #                  key: hostname
            #                  name: eureka-config
            - name: KAFKA_SERVERS
              value: kafka:9092