spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"