server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: ${EUREKA_URI}
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

spring:
  config:
    import:
        - classpath:/application.yaml
  cloud:
    config:
      enabled: false
  application:
    name: eureka-server