spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    discovery:
      enabled: true
    globals:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"

jwt:
  secret: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
  key: JWT_SECRET

authentication:
  enabled: true

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG