server:
  port: 8082

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-public
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/v1/users/login,/api/v1/users/signup
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}

        - id: user-service-protected
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:[*]"
              - "chrome-extension://*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost



jwt:
  secretkey: JWT_SECRET
  secretval: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4